<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_LamparaAsignada_ST" Id="{cb0c5f12-56d6-46fd-b76b-40c9b1cfc97a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LamparaAsignada_ST
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    Lampara AT %Q*: BOOL;
    Pulsador AT %I*: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Lampara := Pulsador;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>