<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_LamparaIntermitente_IL" Id="{ce178025-ba9a-4fc2-92f6-70b394b9bdde}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LamparaIntermitente_IL
// La lampara parpadea de forma continua
VAR_INPUT
    TiempoParpadeo   : TIME := T#500MS;
END_VAR
VAR
    Temporizador     : TON;
    Lampara  AT %Q*  : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Il"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">true</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" cet="ILStatement">
                    <o>
                      <v n="Operator">"CAL"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"Temporizador"</v>
                        <v n="Type">"TON"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">172L</v>
                      </o>
                      <v n="Postfix">"("</v>
                      <v n="Id">171L</v>
                    </o>
                    <o>
                      <v n="Operator">"IN"</v>
                      <v n="Prefix">":="</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"NOT Temporizador.Q"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">174L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">173L</v>
                    </o>
                    <o>
                      <v n="Operator">"PT"</v>
                      <v n="Prefix">":="</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"TiempoParpadeo"</v>
                        <v n="Type">"TIME"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">176L</v>
                      </o>
                      <v n="Postfix">")"</v>
                      <v n="Id">175L</v>
                    </o>
                  </l2>
                  <v n="Comment">"Temporizador auto-pilotado
"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">170L</v>
                </o>
                <o>
                  <v n="ILActive">true</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" cet="ILStatement">
                    <o>
                      <v n="Operator">"LD"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"Temporizador.Q"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">187L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">186L</v>
                    </o>
                    <o>
                      <v n="Operator">"JMPCN"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"End"</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">192L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">191L</v>
                    </o>
                  </l2>
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">185L</v>
                </o>
                <o>
                  <v n="ILActive">true</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" cet="ILStatement">
                    <o>
                      <v n="Operator">"LD "</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"Lampara"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">190L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">189L</v>
                    </o>
                    <o>
                      <v n="Operator">"STN"</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">"Lampara"</v>
                        <v n="Type">"BOOL"</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">194L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">193L</v>
                    </o>
                  </l2>
                  <v n="Comment">"Salida conmutada"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">188L</v>
                </o>
                <o>
                  <v n="ILActive">true</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" cet="ILStatement">
                    <o>
                      <v n="Operator">""</v>
                      <v n="Prefix">""</v>
                      <o n="Operand" t="Operand">
                        <v n="Operand">""</v>
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">false</v>
                        <v n="Id">197L</v>
                      </o>
                      <v n="Postfix">""</v>
                      <v n="Id">196L</v>
                    </o>
                  </l2>
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">"End"</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">195L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="ILStatement">{6a53a656-0ed2-439d-9798-f11da86e9f5e}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>