<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_LamparaAsignada_ST" Id="{fe2f1aec-cd84-4616-b9e1-f05e5fd6791e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LamparaAsignada_ST
// La lampara se enciende mientras se acciona el pulsador
VAR
    Lampara  AT %Q* : BOOL;
    Pulsador AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Lampara := Pulsador;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>